# Generated by Django 3.0.5 on 2020-04-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=30)),
                ('state_province', models.CharField(max_length=25)),
                ('country_id', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
    ]
